### ISSUE TITLE
Multi-Region specification on `ai custom-jobs create`

### ISSUE THREAD

**Issue by herambgadgil** [htappen/r-google-cloud-ai#1]
Hello,

I am trying to replicate the instructions mentioned in this repos training example. But, I am facing an error due to a region discrepancy between `gcs` bucket and the job. 

My `gcs` bucket is in `us (multi-region)`  and if I specify `us-central1` on the job's `region` parameter, I get following error

![image](https://user-images.githubusercontent.com/15884914/113768137-1ff6cf80-973d-11eb-9c49-3ef52fd61da9.png)

If I try to provide `--region=us` or `--region=global`, I get following error

![image](https://user-images.githubusercontent.com/15884914/113768409-7401b400-973d-11eb-87f1-127fc3d636a9.png)

Could you please help me out with this?

Thanks!
Heramb

**Comment by htappen** [comment]
This is an issue with Cloud AI Platform itself. I'll move this conversation into an email thread and come back to you.

**Comment by htappen** [comment]
Not a problem with this code -- it's an issue with Cloud AI Platform.
