### ISSUE TITLE
Connection Refused for runApp()

### ISSUE THREAD

**Issue by herambgadgil** [htappen/r-google-cloud-ai#3]
Hi Henry,

I am encountering yet another problem. When I try to run a shiny app locally, I get a connection refused error. I tried to open a particular port and then set it with `options(shiny.port = xxxx)` and also tried setting the host to `0.0.0.0`. 

But the problem still persists. The app is a simple 'Hello World!'

![image](https://user-images.githubusercontent.com/15884914/121431347-e9d10880-c996-11eb-926b-af9fc237a324.png)

Let me know if this is related to this repo or if I need to raise a support case. Tagging @rajcheval for any additional helpful inputs. 

Thanks!
Heramb

**Comment by htappen** [comment]
This is related to the RStudio and the way it has its own proxy inside. Here's roughly the problem: https://github.com/rstudio/rstudio/blob/master/src/cpp/server_core/UrlPorts.cpp

I have an idea of how to fix this, but I'm not sure it will be easy.

**Comment by htappen** [comment]
Check out the latest update. I think it fixes it.

**Comment by herambgadgil** [comment]
I will check and revert!

**Comment by herambgadgil** [comment]
Hi Henry,

The enhancement works! Thanks a lot.. Cannot emphasize more on how much useful this is! :-)

Thanks!
Heramb
